# Generated by Django 3.2.9 on 2021-11-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_donation_free_appointments',
            name='Date_time',
            field=models.DateTimeField(),
        ),
    ]
