# Generated by Django 3.2.9 on 2021-12-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
