# Generated by Django 3.2.9 on 2021-11-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kill_questions',
            name='expected_answer',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
