# Generated by Django 3.2.9 on 2021-11-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_kill_questions_expected_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_donation_free_appointments',
            name='assigned',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='blood_donation_free_appointments',
            name='reserved',
            field=models.BooleanField(default=1),
        ),
    ]
