# Generated by Django 3.2.9 on 2021-11-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211114_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual_appointment',
            name='name',
        ),
    ]
