# Generated by Django 3.2.9 on 2021-11-14 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_blood_donation_free_appointments_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_donation_appointments',
            name='Date_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.blood_donation_free_appointments'),
        ),
    ]
