# Generated by Django 4.0.dev20210827112741 on 2021-11-28 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_appointment_person_alter_appointment_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.person'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.request'),
        ),
    ]
