# Generated by Django 4.0.dev20210827112741 on 2021-12-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_appointment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
