# Generated by Django 3.2.9 on 2021-11-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20211114_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual_appointment',
            name='appointment_time',
        ),
    ]
