# Generated by Django 4.0.dev20210827112741 on 2021-11-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_appointment_person_alter_appointment_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_id', to='backend.person'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_id', to='backend.request'),
        ),
    ]
