# Generated by Django 3.2.9 on 2021-11-14 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_blood_donation_free_appointments_ymdhm'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual_appointment',
            name='appointment_time',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='backend.blood_donation_free_appointments'),
        ),
    ]
