# Generated by Django 3.2.9 on 2021-11-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_individual_appointment_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_donation_free_appointments',
            name='ymdhm',
            field=models.TextField(default='<django.db.models.fields.IntegerField><django.db.models.fields.IntegerField><django.db.models.fields.IntegerField><django.db.models.fields.IntegerField><django.db.models.fields.IntegerField>'),
        ),
    ]
