# Generated by Django 3.2.9 on 2022-02-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250)),
                ('appointmentLength', models.IntegerField()),
            ],
            options={
                'db_table': 'AdminSettings',
            },
        ),
        migrations.CreateModel(
            name='DonationQuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('donationQuestion', models.IntegerField()),
            ],
            options={
                'db_table': 'DonationQuestionTranslation',
            },
        ),
        migrations.CreateModel(
            name='FaqQuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.TextField()),
                ('body', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('faqQuestion', models.IntegerField()),
            ],
            options={
                'db_table': 'FaqQuestionTranslation',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfFirstTimeDonations', models.IntegerField()),
                ('totalBookedAppointments', models.IntegerField()),
                ('aged18to27', models.IntegerField()),
                ('aged28to37', models.IntegerField()),
                ('aged38to47', models.IntegerField()),
                ('aged48to57', models.IntegerField()),
                ('aged58to68', models.IntegerField()),
                ('acceptedRequests', models.IntegerField()),
                ('rejectedRequests', models.IntegerField()),
                ('cancelledRequests', models.IntegerField()),
            ],
            options={
                'db_table': 'Statistic',
            },
        ),
        migrations.RemoveField(
            model_name='donationquestion',
            name='body',
        ),
        migrations.RemoveField(
            model_name='faqquestion',
            name='body',
        ),
        migrations.RemoveField(
            model_name='faqquestion',
            name='head',
        ),
        migrations.AddField(
            model_name='donationquestion',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='Appointment',
        ),
        migrations.AlterModelTable(
            name='capacity',
            table='Capacity',
        ),
        migrations.AlterModelTable(
            name='donationquestion',
            table='DonationQuestion',
        ),
        migrations.AlterModelTable(
            name='faqquestion',
            table='FaqQuestion',
        ),
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
        migrations.AlterModelTable(
            name='request',
            table='Request',
        ),
    ]
