# Generated by Django 4.0.1 on 2022-01-23 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250)),
                ('appointmentLength', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfFirstTimeDonations', models.IntegerField()),
                ('totalBookedAppointments', models.IntegerField()),
                ('aged18to27', models.IntegerField()),
                ('aged28to37', models.IntegerField()),
                ('aged38to47', models.IntegerField()),
                ('aged48to57', models.IntegerField()),
                ('aged58to68', models.IntegerField()),
                ('acceptedRequests', models.IntegerField()),
                ('rejectedRequests', models.IntegerField()),
                ('cancelledRequests', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='donationquestion',
            name='body',
        ),
        migrations.RemoveField(
            model_name='faqquestion',
            name='body',
        ),
        migrations.RemoveField(
            model_name='faqquestion',
            name='head',
        ),
        migrations.AddField(
            model_name='donationquestion',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='FaqQuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('language', models.CharField(max_length=250)),
                ('faqQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.faqquestion')),
            ],
        ),
        migrations.CreateModel(
            name='DonationQuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('language', models.CharField(max_length=250)),
                ('faqQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.donationquestion')),
            ],
        ),
    ]
