# Generated by Django 3.2.9 on 2022-02-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20220227_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationquestion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donationquestiontranslation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faqquestiontranslation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
