# Generated by Django 4.0.1 on 2022-01-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_adminsettings_statistic_remove_donationquestion_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationquestiontranslation',
            old_name='faqQuestion',
            new_name='donationQuestion',
        ),
    ]
