# Generated by Django 3.2.9 on 2022-01-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_rename_faqquestion_donationquestiontranslation_donationquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationquestion',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
