# Generated by Django 3.2.9 on 2022-01-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20220126_1511'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='capacity',
            table='KKK',
        ),
    ]
