# Generated by Django 3.2.9 on 2022-01-26 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250)),
                ('appointmentLength', models.IntegerField()),
            ],
            options={
                'db_table': 'AdminSettings',
            },
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('slots', models.IntegerField()),
            ],
            options={
                'db_table': 'Capacity',
            },
        ),
        migrations.CreateModel(
            name='DonationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=1)),
                ('isYesCorrect', models.BooleanField()),
            ],
            options={
                'db_table': 'DonationQuestion',
            },
        ),
        migrations.CreateModel(
            name='FaqQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'FaqQuestion',
            },
        ),
        migrations.CreateModel(
            name='OnboardingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('head', models.CharField(max_length=250)),
                ('body', models.TextField(max_length=250)),
                ('image', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'OnboardingPage',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=12, null=True)),
                ('firstDonation', models.BooleanField(blank=True, default=False, null=True)),
                ('telephoneNumber', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Request',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfFirstTimeDonations', models.IntegerField()),
                ('totalBookedAppointments', models.IntegerField()),
                ('aged18to27', models.IntegerField()),
                ('aged28to37', models.IntegerField()),
                ('aged38to47', models.IntegerField()),
                ('aged48to57', models.IntegerField()),
                ('aged58to68', models.IntegerField()),
                ('acceptedRequests', models.IntegerField()),
                ('rejectedRequests', models.IntegerField()),
                ('cancelledRequests', models.IntegerField()),
            ],
            options={
                'db_table': 'Statistic',
            },
        ),
        migrations.CreateModel(
            name='FaqQuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('language', models.CharField(max_length=250)),
                ('faqQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websocket.faqquestion')),
            ],
            options={
                'db_table': 'FaqQuestionTranslation',
            },
        ),
        migrations.CreateModel(
            name='DonationQuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('language', models.CharField(max_length=250)),
                ('donationQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websocket.donationquestion')),
            ],
            options={
                'db_table': 'DonationQuestionTranslation',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websocket.person')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websocket.request')),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
    ]
