# Generated by Django 3.2.9 on 2022-02-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationquestiontranslation',
            name='head',
        ),
        migrations.AlterField(
            model_name='donationquestion',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donationquestiontranslation',
            name='donationQuestion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donationquestiontranslation',
            name='language',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faqquestiontranslation',
            name='faqQuestion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='faqquestiontranslation',
            name='head',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faqquestiontranslation',
            name='language',
            field=models.CharField(max_length=10),
        ),
    ]
