# Generated by Django 3.2.9 on 2022-03-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0003_auto_20220227_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationquestiontranslation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
