# Generated by Django 3.2.11 on 2022-01-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaqQuestion',
        ),
    ]
