# Generated by Django 3.2.9 on 2022-01-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='capacity',
            table='KKK',
        ),
    ]
