# Generated by Django 3.2.11 on 2022-01-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_delete_faqquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationquestion',
            name='body',
        ),
        migrations.AddField(
            model_name='donationquestion',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
