# Generated by Django 3.2.9 on 2022-01-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_capacity_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='capacity',
            table=None,
        ),
    ]
